-d E:\hbird\xianshi_1\impl\gwsynthesis\top.vg
-p GW2A-18C-PBGA256-8
-pn GW2A-LV18PG256C8/I7
-cst E:\hbird\xianshi_1\src\top.cst
-cfg E:\hbird\xianshi_1\impl\pnr\device.cfg
-sdc E:\hbird\xianshi_1\src\lcd.sdc
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
